version: '3'
services:
  fastfood_app:
    depends_on:
      postgres:
        condition: service_healthy  
    container_name: fastfood_app
    volumes:
      - ./:/app
    build: .
    ports:
      - "8000:8000"