version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # Porta para o LocalStack
      - "8080:8080" # Porta para o DynamoDB local
    environment:
      - SERVICES=dynamodb
  fastfood_app:
    depends_on:
        localstack:
          condition: service_healthy  
    container_name: fastfood_order_production_app
    volumes:
      - ./:/app
    environment:
      - ENVIRONMENT=development
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    build: .
    ports:
      - "8000:8000"