name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0
      
      - name: Install dependencies
        run: go mod download

      - name: Generate mocks
        run: go generate ./...
      
      - name: Run tests
        run: go test $(go list ./internal/... | grep -v /mock)